//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    public partial class T_adImage: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string adCode
        {
            get { return _adCode; }
            set
            {
                if (_adCode != value)
                {
                    _adCode = value;
                    OnPropertyChanged("adCode");
                }
            }
        }
        private string _adCode;
    
        [DataMember]
        public string imgUrl
        {
            get { return _imgUrl; }
            set
            {
                if (_imgUrl != value)
                {
                    _imgUrl = value;
                    OnPropertyChanged("imgUrl");
                }
            }
        }
        private string _imgUrl;
    
        [DataMember]
        public string httpUrl
        {
            get { return _httpUrl; }
            set
            {
                if (_httpUrl != value)
                {
                    _httpUrl = value;
                    OnPropertyChanged("httpUrl");
                }
            }
        }
        private string _httpUrl;
    
        [DataMember]
        public string imgcaption
        {
            get { return _imgcaption; }
            set
            {
                if (_imgcaption != value)
                {
                    _imgcaption = value;
                    OnPropertyChanged("imgcaption");
                }
            }
        }
        private string _imgcaption;
    
        [DataMember]
        public string imgAlt
        {
            get { return _imgAlt; }
            set
            {
                if (_imgAlt != value)
                {
                    _imgAlt = value;
                    OnPropertyChanged("imgAlt");
                }
            }
        }
        private string _imgAlt;
    
        [DataMember]
        public string tag1
        {
            get { return _tag1; }
            set
            {
                if (_tag1 != value)
                {
                    _tag1 = value;
                    OnPropertyChanged("tag1");
                }
            }
        }
        private string _tag1;
    
        [DataMember]
        public string tag2
        {
            get { return _tag2; }
            set
            {
                if (_tag2 != value)
                {
                    _tag2 = value;
                    OnPropertyChanged("tag2");
                }
            }
        }
        private string _tag2;
    
        [DataMember]
        public string tag3
        {
            get { return _tag3; }
            set
            {
                if (_tag3 != value)
                {
                    _tag3 = value;
                    OnPropertyChanged("tag3");
                }
            }
        }
        private string _tag3;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
