//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    public partial class T_DarryMsg: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int DarryMsgId
        {
            get { return _darryMsgId; }
            set
            {
                if (_darryMsgId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“DarryMsgId”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _darryMsgId = value;
                    OnPropertyChanged("DarryMsgId");
                }
            }
        }
        private int _darryMsgId;
    
        [DataMember]
        public string DarryMsgContent
        {
            get { return _darryMsgContent; }
            set
            {
                if (_darryMsgContent != value)
                {
                    _darryMsgContent = value;
                    OnPropertyChanged("DarryMsgContent");
                }
            }
        }
        private string _darryMsgContent;
    
        [DataMember]
        public Nullable<System.DateTime> DarryMsgAddtime
        {
            get { return _darryMsgAddtime; }
            set
            {
                if (_darryMsgAddtime != value)
                {
                    _darryMsgAddtime = value;
                    OnPropertyChanged("DarryMsgAddtime");
                }
            }
        }
        private Nullable<System.DateTime> _darryMsgAddtime;
    
        [DataMember]
        public string DarryMsgPostip
        {
            get { return _darryMsgPostip; }
            set
            {
                if (_darryMsgPostip != value)
                {
                    _darryMsgPostip = value;
                    OnPropertyChanged("DarryMsgPostip");
                }
            }
        }
        private string _darryMsgPostip;
    
        [DataMember]
        public string DarryMsgUserName
        {
            get { return _darryMsgUserName; }
            set
            {
                if (_darryMsgUserName != value)
                {
                    _darryMsgUserName = value;
                    OnPropertyChanged("DarryMsgUserName");
                }
            }
        }
        private string _darryMsgUserName;
    
        [DataMember]
        public string DarryMsgReply
        {
            get { return _darryMsgReply; }
            set
            {
                if (_darryMsgReply != value)
                {
                    _darryMsgReply = value;
                    OnPropertyChanged("DarryMsgReply");
                }
            }
        }
        private string _darryMsgReply;
    
        [DataMember]
        public Nullable<int> DiySearchId
        {
            get { return _diySearchId; }
            set
            {
                if (_diySearchId != value)
                {
                    _diySearchId = value;
                    OnPropertyChanged("DiySearchId");
                }
            }
        }
        private Nullable<int> _diySearchId;
    
        [DataMember]
        public Nullable<System.DateTime> DarryMsgReAddtime
        {
            get { return _darryMsgReAddtime; }
            set
            {
                if (_darryMsgReAddtime != value)
                {
                    _darryMsgReAddtime = value;
                    OnPropertyChanged("DarryMsgReAddtime");
                }
            }
        }
        private Nullable<System.DateTime> _darryMsgReAddtime;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
