//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    public partial class T_DarryHome: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int DarryHomeId
        {
            get { return _darryHomeId; }
            set
            {
                if (_darryHomeId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“DarryHomeId”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _darryHomeId = value;
                    OnPropertyChanged("DarryHomeId");
                }
            }
        }
        private int _darryHomeId;
    
        [DataMember]
        public Nullable<int> DarryHomeMemberId
        {
            get { return _darryHomeMemberId; }
            set
            {
                if (_darryHomeMemberId != value)
                {
                    _darryHomeMemberId = value;
                    OnPropertyChanged("DarryHomeMemberId");
                }
            }
        }
        private Nullable<int> _darryHomeMemberId;
    
        [DataMember]
        public string DarryHomeMemberName
        {
            get { return _darryHomeMemberName; }
            set
            {
                if (_darryHomeMemberName != value)
                {
                    _darryHomeMemberName = value;
                    OnPropertyChanged("DarryHomeMemberName");
                }
            }
        }
        private string _darryHomeMemberName;
    
        [DataMember]
        public string DarryHomeNationality
        {
            get { return _darryHomeNationality; }
            set
            {
                if (_darryHomeNationality != value)
                {
                    _darryHomeNationality = value;
                    OnPropertyChanged("DarryHomeNationality");
                }
            }
        }
        private string _darryHomeNationality;
    
        [DataMember]
        public string DarryHomeIDCard
        {
            get { return _darryHomeIDCard; }
            set
            {
                if (_darryHomeIDCard != value)
                {
                    _darryHomeIDCard = value;
                    OnPropertyChanged("DarryHomeIDCard");
                }
            }
        }
        private string _darryHomeIDCard;
    
        [DataMember]
        public string DarryHomeOrderId
        {
            get { return _darryHomeOrderId; }
            set
            {
                if (_darryHomeOrderId != value)
                {
                    _darryHomeOrderId = value;
                    OnPropertyChanged("DarryHomeOrderId");
                }
            }
        }
        private string _darryHomeOrderId;
    
        [DataMember]
        public bool DarryHomeIsBit
        {
            get { return _darryHomeIsBit; }
            set
            {
                if (_darryHomeIsBit != value)
                {
                    _darryHomeIsBit = value;
                    OnPropertyChanged("DarryHomeIsBit");
                }
            }
        }
        private bool _darryHomeIsBit;
    
        [DataMember]
        public Nullable<System.DateTime> DarryHomeDate
        {
            get { return _darryHomeDate; }
            set
            {
                if (_darryHomeDate != value)
                {
                    _darryHomeDate = value;
                    OnPropertyChanged("DarryHomeDate");
                }
            }
        }
        private Nullable<System.DateTime> _darryHomeDate;
    
        [DataMember]
        public string DarryHomeMemberTitle
        {
            get { return _darryHomeMemberTitle; }
            set
            {
                if (_darryHomeMemberTitle != value)
                {
                    _darryHomeMemberTitle = value;
                    OnPropertyChanged("DarryHomeMemberTitle");
                }
            }
        }
        private string _darryHomeMemberTitle;
    
        [DataMember]
        public string DarryHomeMsName
        {
            get { return _darryHomeMsName; }
            set
            {
                if (_darryHomeMsName != value)
                {
                    _darryHomeMsName = value;
                    OnPropertyChanged("DarryHomeMsName");
                }
            }
        }
        private string _darryHomeMsName;
    
        [DataMember]
        public string DarryHomeContent
        {
            get { return _darryHomeContent; }
            set
            {
                if (_darryHomeContent != value)
                {
                    _darryHomeContent = value;
                    OnPropertyChanged("DarryHomeContent");
                }
            }
        }
        private string _darryHomeContent;
    
        [DataMember]
        public string DarryHomeCode
        {
            get { return _darryHomeCode; }
            set
            {
                if (_darryHomeCode != value)
                {
                    _darryHomeCode = value;
                    OnPropertyChanged("DarryHomeCode");
                }
            }
        }
        private string _darryHomeCode;
    
        [DataMember]
        public string DarryHomePhoto
        {
            get { return _darryHomePhoto; }
            set
            {
                if (_darryHomePhoto != value)
                {
                    _darryHomePhoto = value;
                    OnPropertyChanged("DarryHomePhoto");
                }
            }
        }
        private string _darryHomePhoto;
    
        [DataMember]
        public string DarryHomeBgPhoto
        {
            get { return _darryHomeBgPhoto; }
            set
            {
                if (_darryHomeBgPhoto != value)
                {
                    _darryHomeBgPhoto = value;
                    OnPropertyChanged("DarryHomeBgPhoto");
                }
            }
        }
        private string _darryHomeBgPhoto;
    
        [DataMember]
        public string DarryHomeMusicUrl
        {
            get { return _darryHomeMusicUrl; }
            set
            {
                if (_darryHomeMusicUrl != value)
                {
                    _darryHomeMusicUrl = value;
                    OnPropertyChanged("DarryHomeMusicUrl");
                }
            }
        }
        private string _darryHomeMusicUrl;
    
        [DataMember]
        public string DarryHomeProductImg
        {
            get { return _darryHomeProductImg; }
            set
            {
                if (_darryHomeProductImg != value)
                {
                    _darryHomeProductImg = value;
                    OnPropertyChanged("DarryHomeProductImg");
                }
            }
        }
        private string _darryHomeProductImg;
    
        [DataMember]
        public string DarryHomeIDCardMd5
        {
            get { return _darryHomeIDCardMd5; }
            set
            {
                if (_darryHomeIDCardMd5 != value)
                {
                    _darryHomeIDCardMd5 = value;
                    OnPropertyChanged("DarryHomeIDCardMd5");
                }
            }
        }
        private string _darryHomeIDCardMd5;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
