//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    public partial class T_LoveMap: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int MapId
        {
            get { return _mapId; }
            set
            {
                if (_mapId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“MapId”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _mapId = value;
                    OnPropertyChanged("MapId");
                }
            }
        }
        private int _mapId;
    
        [DataMember]
        public string MapName
        {
            get { return _mapName; }
            set
            {
                if (_mapName != value)
                {
                    _mapName = value;
                    OnPropertyChanged("MapName");
                }
            }
        }
        private string _mapName;
    
        [DataMember]
        public string MapCon
        {
            get { return _mapCon; }
            set
            {
                if (_mapCon != value)
                {
                    _mapCon = value;
                    OnPropertyChanged("MapCon");
                }
            }
        }
        private string _mapCon;
    
        [DataMember]
        public string Maplng
        {
            get { return _maplng; }
            set
            {
                if (_maplng != value)
                {
                    _maplng = value;
                    OnPropertyChanged("Maplng");
                }
            }
        }
        private string _maplng;
    
        [DataMember]
        public string Maplat
        {
            get { return _maplat; }
            set
            {
                if (_maplat != value)
                {
                    _maplat = value;
                    OnPropertyChanged("Maplat");
                }
            }
        }
        private string _maplat;
    
        [DataMember]
        public string MapIp
        {
            get { return _mapIp; }
            set
            {
                if (_mapIp != value)
                {
                    _mapIp = value;
                    OnPropertyChanged("MapIp");
                }
            }
        }
        private string _mapIp;
    
        [DataMember]
        public Nullable<System.DateTime> MapDate
        {
            get { return _mapDate; }
            set
            {
                if (_mapDate != value)
                {
                    _mapDate = value;
                    OnPropertyChanged("MapDate");
                }
            }
        }
        private Nullable<System.DateTime> _mapDate;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
