//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(T_memAlbum))]
    public partial class T_memPhoto: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int photo_id
        {
            get { return _photo_id; }
            set
            {
                if (_photo_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“photo_id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _photo_id = value;
                    OnPropertyChanged("photo_id");
                }
            }
        }
        private int _photo_id;
    
        [DataMember]
        public Nullable<int> album_id
        {
            get { return _album_id; }
            set
            {
                if (_album_id != value)
                {
                    ChangeTracker.RecordOriginalValue("album_id", _album_id);
                    if (!IsDeserializing)
                    {
                        if (T_memAlbum != null && T_memAlbum.album_id != value)
                        {
                            T_memAlbum = null;
                        }
                    }
                    _album_id = value;
                    OnPropertyChanged("album_id");
                }
            }
        }
        private Nullable<int> _album_id;
    
        [DataMember]
        public string photo_path
        {
            get { return _photo_path; }
            set
            {
                if (_photo_path != value)
                {
                    _photo_path = value;
                    OnPropertyChanged("photo_path");
                }
            }
        }
        private string _photo_path;
    
        [DataMember]
        public Nullable<System.DateTime> photo_time
        {
            get { return _photo_time; }
            set
            {
                if (_photo_time != value)
                {
                    _photo_time = value;
                    OnPropertyChanged("photo_time");
                }
            }
        }
        private Nullable<System.DateTime> _photo_time;

        #endregion

        #region 导航属性
    
        [DataMember]
        public T_memAlbum T_memAlbum
        {
            get { return _t_memAlbum; }
            set
            {
                if (!ReferenceEquals(_t_memAlbum, value))
                {
                    var previousValue = _t_memAlbum;
                    _t_memAlbum = value;
                    FixupT_memAlbum(previousValue);
                    OnNavigationPropertyChanged("T_memAlbum");
                }
            }
        }
        private T_memAlbum _t_memAlbum;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            T_memAlbum = null;
        }

        #endregion

        #region 关联修复
    
        private void FixupT_memAlbum(T_memAlbum previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.T_memPhoto.Contains(this))
            {
                previousValue.T_memPhoto.Remove(this);
            }
    
            if (T_memAlbum != null)
            {
                if (!T_memAlbum.T_memPhoto.Contains(this))
                {
                    T_memAlbum.T_memPhoto.Add(this);
                }
    
                album_id = T_memAlbum.album_id;
            }
            else if (!skipKeys)
            {
                album_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("T_memAlbum")
                    && (ChangeTracker.OriginalValues["T_memAlbum"] == T_memAlbum))
                {
                    ChangeTracker.OriginalValues.Remove("T_memAlbum");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("T_memAlbum", previousValue);
                }
                if (T_memAlbum != null && !T_memAlbum.ChangeTracker.ChangeTrackingEnabled)
                {
                    T_memAlbum.StartTracking();
                }
            }
        }

        #endregion

    }
}
