//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    public partial class T_Product: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ProductId”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _productId = value;
                    OnPropertyChanged("ProductId");
                }
            }
        }
        private int _productId;
    
        [DataMember]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    _title = value;
                    OnPropertyChanged("Title");
                }
            }
        }
        private string _title;
    
        [DataMember]
        public string p_content
        {
            get { return _p_content; }
            set
            {
                if (_p_content != value)
                {
                    _p_content = value;
                    OnPropertyChanged("p_content");
                }
            }
        }
        private string _p_content;
    
        [DataMember]
        public Nullable<int> classid
        {
            get { return _classid; }
            set
            {
                if (_classid != value)
                {
                    _classid = value;
                    OnPropertyChanged("classid");
                }
            }
        }
        private Nullable<int> _classid;
    
        [DataMember]
        public string Price
        {
            get { return _price; }
            set
            {
                if (_price != value)
                {
                    _price = value;
                    OnPropertyChanged("Price");
                }
            }
        }
        private string _price;
    
        [DataMember]
        public Nullable<decimal> MemberPrice
        {
            get { return _memberPrice; }
            set
            {
                if (_memberPrice != value)
                {
                    _memberPrice = value;
                    OnPropertyChanged("MemberPrice");
                }
            }
        }
        private Nullable<decimal> _memberPrice;
    
        [DataMember]
        public Nullable<int> showtime
        {
            get { return _showtime; }
            set
            {
                if (_showtime != value)
                {
                    _showtime = value;
                    OnPropertyChanged("showtime");
                }
            }
        }
        private Nullable<int> _showtime;
    
        [DataMember]
        public string imgurl
        {
            get { return _imgurl; }
            set
            {
                if (_imgurl != value)
                {
                    _imgurl = value;
                    OnPropertyChanged("imgurl");
                }
            }
        }
        private string _imgurl;
    
        [DataMember]
        public Nullable<System.DateTime> addtime
        {
            get { return _addtime; }
            set
            {
                if (_addtime != value)
                {
                    _addtime = value;
                    OnPropertyChanged("addtime");
                }
            }
        }
        private Nullable<System.DateTime> _addtime;
    
        [DataMember]
        public string imgurl1
        {
            get { return _imgurl1; }
            set
            {
                if (_imgurl1 != value)
                {
                    _imgurl1 = value;
                    OnPropertyChanged("imgurl1");
                }
            }
        }
        private string _imgurl1;
    
        [DataMember]
        public string imgurl2
        {
            get { return _imgurl2; }
            set
            {
                if (_imgurl2 != value)
                {
                    _imgurl2 = value;
                    OnPropertyChanged("imgurl2");
                }
            }
        }
        private string _imgurl2;
    
        [DataMember]
        public string imgurl3
        {
            get { return _imgurl3; }
            set
            {
                if (_imgurl3 != value)
                {
                    _imgurl3 = value;
                    OnPropertyChanged("imgurl3");
                }
            }
        }
        private string _imgurl3;
    
        [DataMember]
        public string imgurl4
        {
            get { return _imgurl4; }
            set
            {
                if (_imgurl4 != value)
                {
                    _imgurl4 = value;
                    OnPropertyChanged("imgurl4");
                }
            }
        }
        private string _imgurl4;
    
        [DataMember]
        public string imgurl5
        {
            get { return _imgurl5; }
            set
            {
                if (_imgurl5 != value)
                {
                    _imgurl5 = value;
                    OnPropertyChanged("imgurl5");
                }
            }
        }
        private string _imgurl5;
    
        [DataMember]
        public Nullable<int> display
        {
            get { return _display; }
            set
            {
                if (_display != value)
                {
                    _display = value;
                    OnPropertyChanged("display");
                }
            }
        }
        private Nullable<int> _display;
    
        [DataMember]
        public Nullable<int> Inventory
        {
            get { return _inventory; }
            set
            {
                if (_inventory != value)
                {
                    _inventory = value;
                    OnPropertyChanged("Inventory");
                }
            }
        }
        private Nullable<int> _inventory;
    
        [DataMember]
        public string text_1
        {
            get { return _text_1; }
            set
            {
                if (_text_1 != value)
                {
                    _text_1 = value;
                    OnPropertyChanged("text_1");
                }
            }
        }
        private string _text_1;
    
        [DataMember]
        public string text_2
        {
            get { return _text_2; }
            set
            {
                if (_text_2 != value)
                {
                    _text_2 = value;
                    OnPropertyChanged("text_2");
                }
            }
        }
        private string _text_2;
    
        [DataMember]
        public string text_3
        {
            get { return _text_3; }
            set
            {
                if (_text_3 != value)
                {
                    _text_3 = value;
                    OnPropertyChanged("text_3");
                }
            }
        }
        private string _text_3;
    
        [DataMember]
        public string text_4
        {
            get { return _text_4; }
            set
            {
                if (_text_4 != value)
                {
                    _text_4 = value;
                    OnPropertyChanged("text_4");
                }
            }
        }
        private string _text_4;
    
        [DataMember]
        public string text_5
        {
            get { return _text_5; }
            set
            {
                if (_text_5 != value)
                {
                    _text_5 = value;
                    OnPropertyChanged("text_5");
                }
            }
        }
        private string _text_5;
    
        [DataMember]
        public string text_6
        {
            get { return _text_6; }
            set
            {
                if (_text_6 != value)
                {
                    _text_6 = value;
                    OnPropertyChanged("text_6");
                }
            }
        }
        private string _text_6;
    
        [DataMember]
        public string text_7
        {
            get { return _text_7; }
            set
            {
                if (_text_7 != value)
                {
                    _text_7 = value;
                    OnPropertyChanged("text_7");
                }
            }
        }
        private string _text_7;
    
        [DataMember]
        public string text_8
        {
            get { return _text_8; }
            set
            {
                if (_text_8 != value)
                {
                    _text_8 = value;
                    OnPropertyChanged("text_8");
                }
            }
        }
        private string _text_8;
    
        [DataMember]
        public string text_9
        {
            get { return _text_9; }
            set
            {
                if (_text_9 != value)
                {
                    _text_9 = value;
                    OnPropertyChanged("text_9");
                }
            }
        }
        private string _text_9;
    
        [DataMember]
        public string text_10
        {
            get { return _text_10; }
            set
            {
                if (_text_10 != value)
                {
                    _text_10 = value;
                    OnPropertyChanged("text_10");
                }
            }
        }
        private string _text_10;
    
        [DataMember]
        public string text_11
        {
            get { return _text_11; }
            set
            {
                if (_text_11 != value)
                {
                    _text_11 = value;
                    OnPropertyChanged("text_11");
                }
            }
        }
        private string _text_11;
    
        [DataMember]
        public string text_12
        {
            get { return _text_12; }
            set
            {
                if (_text_12 != value)
                {
                    _text_12 = value;
                    OnPropertyChanged("text_12");
                }
            }
        }
        private string _text_12;
    
        [DataMember]
        public string text_13
        {
            get { return _text_13; }
            set
            {
                if (_text_13 != value)
                {
                    _text_13 = value;
                    OnPropertyChanged("text_13");
                }
            }
        }
        private string _text_13;
    
        [DataMember]
        public string text_14
        {
            get { return _text_14; }
            set
            {
                if (_text_14 != value)
                {
                    _text_14 = value;
                    OnPropertyChanged("text_14");
                }
            }
        }
        private string _text_14;
    
        [DataMember]
        public string text_15
        {
            get { return _text_15; }
            set
            {
                if (_text_15 != value)
                {
                    _text_15 = value;
                    OnPropertyChanged("text_15");
                }
            }
        }
        private string _text_15;
    
        [DataMember]
        public string text_16
        {
            get { return _text_16; }
            set
            {
                if (_text_16 != value)
                {
                    _text_16 = value;
                    OnPropertyChanged("text_16");
                }
            }
        }
        private string _text_16;
    
        [DataMember]
        public string text_17
        {
            get { return _text_17; }
            set
            {
                if (_text_17 != value)
                {
                    _text_17 = value;
                    OnPropertyChanged("text_17");
                }
            }
        }
        private string _text_17;
    
        [DataMember]
        public string text_18
        {
            get { return _text_18; }
            set
            {
                if (_text_18 != value)
                {
                    _text_18 = value;
                    OnPropertyChanged("text_18");
                }
            }
        }
        private string _text_18;
    
        [DataMember]
        public string text_19
        {
            get { return _text_19; }
            set
            {
                if (_text_19 != value)
                {
                    _text_19 = value;
                    OnPropertyChanged("text_19");
                }
            }
        }
        private string _text_19;
    
        [DataMember]
        public string text_20
        {
            get { return _text_20; }
            set
            {
                if (_text_20 != value)
                {
                    _text_20 = value;
                    OnPropertyChanged("text_20");
                }
            }
        }
        private string _text_20;
    
        [DataMember]
        public string pro_no
        {
            get { return _pro_no; }
            set
            {
                if (_pro_no != value)
                {
                    _pro_no = value;
                    OnPropertyChanged("pro_no");
                }
            }
        }
        private string _pro_no;
    
        [DataMember]
        public string cert_type
        {
            get { return _cert_type; }
            set
            {
                if (_cert_type != value)
                {
                    _cert_type = value;
                    OnPropertyChanged("cert_type");
                }
            }
        }
        private string _cert_type;
    
        [DataMember]
        public string cert_no
        {
            get { return _cert_no; }
            set
            {
                if (_cert_no != value)
                {
                    _cert_no = value;
                    OnPropertyChanged("cert_no");
                }
            }
        }
        private string _cert_no;
    
        [DataMember]
        public string pro_attribute
        {
            get { return _pro_attribute; }
            set
            {
                if (_pro_attribute != value)
                {
                    _pro_attribute = value;
                    OnPropertyChanged("pro_attribute");
                }
            }
        }
        private string _pro_attribute;
    
        [DataMember]
        public Nullable<int> istj
        {
            get { return _istj; }
            set
            {
                if (_istj != value)
                {
                    _istj = value;
                    OnPropertyChanged("istj");
                }
            }
        }
        private Nullable<int> _istj;
    
        [DataMember]
        public Nullable<int> sort
        {
            get { return _sort; }
            set
            {
                if (_sort != value)
                {
                    _sort = value;
                    OnPropertyChanged("sort");
                }
            }
        }
        private Nullable<int> _sort;
    
        [DataMember]
        public string handsize
        {
            get { return _handsize; }
            set
            {
                if (_handsize != value)
                {
                    _handsize = value;
                    OnPropertyChanged("handsize");
                }
            }
        }
        private string _handsize;
    
        [DataMember]
        public Nullable<int> diybit
        {
            get { return _diybit; }
            set
            {
                if (_diybit != value)
                {
                    _diybit = value;
                    OnPropertyChanged("diybit");
                }
            }
        }
        private Nullable<int> _diybit;
    
        [DataMember]
        public Nullable<int> diyDiamond
        {
            get { return _diyDiamond; }
            set
            {
                if (_diyDiamond != value)
                {
                    _diyDiamond = value;
                    OnPropertyChanged("diyDiamond");
                }
            }
        }
        private Nullable<int> _diyDiamond;
    
        [DataMember]
        public Nullable<int> diysubDiamond
        {
            get { return _diysubDiamond; }
            set
            {
                if (_diysubDiamond != value)
                {
                    _diysubDiamond = value;
                    OnPropertyChanged("diysubDiamond");
                }
            }
        }
        private Nullable<int> _diysubDiamond;
    
        [DataMember]
        public Nullable<decimal> diyStylePrice
        {
            get { return _diyStylePrice; }
            set
            {
                if (_diyStylePrice != value)
                {
                    _diyStylePrice = value;
                    OnPropertyChanged("diyStylePrice");
                }
            }
        }
        private Nullable<decimal> _diyStylePrice;
    
        [DataMember]
        public Nullable<int> isindex
        {
            get { return _isindex; }
            set
            {
                if (_isindex != value)
                {
                    _isindex = value;
                    OnPropertyChanged("isindex");
                }
            }
        }
        private Nullable<int> _isindex;
    
        [DataMember]
        public string caizhi
        {
            get { return _caizhi; }
            set
            {
                if (_caizhi != value)
                {
                    _caizhi = value;
                    OnPropertyChanged("caizhi");
                }
            }
        }
        private string _caizhi;
    
        [DataMember]
        public string kuanshi
        {
            get { return _kuanshi; }
            set
            {
                if (_kuanshi != value)
                {
                    _kuanshi = value;
                    OnPropertyChanged("kuanshi");
                }
            }
        }
        private string _kuanshi;
    
        [DataMember]
        public Nullable<int> sellcount
        {
            get { return _sellcount; }
            set
            {
                if (_sellcount != value)
                {
                    _sellcount = value;
                    OnPropertyChanged("sellcount");
                }
            }
        }
        private Nullable<int> _sellcount;
    
        [DataMember]
        public Nullable<int> IsXSQG
        {
            get { return _isXSQG; }
            set
            {
                if (_isXSQG != value)
                {
                    _isXSQG = value;
                    OnPropertyChanged("IsXSQG");
                }
            }
        }
        private Nullable<int> _isXSQG;
    
        [DataMember]
        public Nullable<System.DateTime> QGStartTime
        {
            get { return _qGStartTime; }
            set
            {
                if (_qGStartTime != value)
                {
                    _qGStartTime = value;
                    OnPropertyChanged("QGStartTime");
                }
            }
        }
        private Nullable<System.DateTime> _qGStartTime;
    
        [DataMember]
        public Nullable<System.DateTime> QGEndTime
        {
            get { return _qGEndTime; }
            set
            {
                if (_qGEndTime != value)
                {
                    _qGEndTime = value;
                    OnPropertyChanged("QGEndTime");
                }
            }
        }
        private Nullable<System.DateTime> _qGEndTime;
    
        [DataMember]
        public string Shouxing
        {
            get { return _shouxing; }
            set
            {
                if (_shouxing != value)
                {
                    _shouxing = value;
                    OnPropertyChanged("Shouxing");
                }
            }
        }
        private string _shouxing;
    
        [DataMember]
        public Nullable<int> DiamondId
        {
            get { return _diamondId; }
            set
            {
                if (_diamondId != value)
                {
                    _diamondId = value;
                    OnPropertyChanged("DiamondId");
                }
            }
        }
        private Nullable<int> _diamondId;
    
        [DataMember]
        public Nullable<int> prot_id
        {
            get { return _prot_id; }
            set
            {
                if (_prot_id != value)
                {
                    _prot_id = value;
                    OnPropertyChanged("prot_id");
                }
            }
        }
        private Nullable<int> _prot_id;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
