//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DRM.Entity
{
    [DataContract(IsReference = true)]
    public partial class view_diyproduct: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public int BasePID
        {
            get { return _basePID; }
            set
            {
                if (_basePID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“BasePID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _basePID = value;
                    OnPropertyChanged("BasePID");
                }
            }
        }
        private int _basePID;
    
        [DataMember]
        public string productNo
        {
            get { return _productNo; }
            set
            {
                if (_productNo != value)
                {
                    _productNo = value;
                    OnPropertyChanged("productNo");
                }
            }
        }
        private string _productNo;
    
        [DataMember]
        public Nullable<int> productTypeId
        {
            get { return _productTypeId; }
            set
            {
                if (_productTypeId != value)
                {
                    _productTypeId = value;
                    OnPropertyChanged("productTypeId");
                }
            }
        }
        private Nullable<int> _productTypeId;
    
        [DataMember]
        public string ProductType
        {
            get { return _productType; }
            set
            {
                if (_productType != value)
                {
                    _productType = value;
                    OnPropertyChanged("ProductType");
                }
            }
        }
        private string _productType;
    
        [DataMember]
        public string title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    _title = value;
                    OnPropertyChanged("title");
                }
            }
        }
        private string _title;
    
        [DataMember]
        public string p_content
        {
            get { return _p_content; }
            set
            {
                if (_p_content != value)
                {
                    _p_content = value;
                    OnPropertyChanged("p_content");
                }
            }
        }
        private string _p_content;
    
        [DataMember]
        public Nullable<System.DateTime> addtime
        {
            get { return _addtime; }
            set
            {
                if (_addtime != value)
                {
                    _addtime = value;
                    OnPropertyChanged("addtime");
                }
            }
        }
        private Nullable<System.DateTime> _addtime;
    
        [DataMember]
        public Nullable<int> status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("status");
                }
            }
        }
        private Nullable<int> _status;
    
        [DataMember]
        public Nullable<int> pSort
        {
            get { return _pSort; }
            set
            {
                if (_pSort != value)
                {
                    _pSort = value;
                    OnPropertyChanged("pSort");
                }
            }
        }
        private Nullable<int> _pSort;
    
        [DataMember]
        public Nullable<int> salecount
        {
            get { return _salecount; }
            set
            {
                if (_salecount != value)
                {
                    _salecount = value;
                    OnPropertyChanged("salecount");
                }
            }
        }
        private Nullable<int> _salecount;
    
        [DataMember]
        public Nullable<int> oldId
        {
            get { return _oldId; }
            set
            {
                if (_oldId != value)
                {
                    _oldId = value;
                    OnPropertyChanged("oldId");
                }
            }
        }
        private Nullable<int> _oldId;
    
        [DataMember]
        public string CollectionId
        {
            get { return _collectionId; }
            set
            {
                if (_collectionId != value)
                {
                    _collectionId = value;
                    OnPropertyChanged("CollectionId");
                }
            }
        }
        private string _collectionId;
    
        [DataMember]
        public Nullable<int> fDiamondId
        {
            get { return _fDiamondId; }
            set
            {
                if (_fDiamondId != value)
                {
                    _fDiamondId = value;
                    OnPropertyChanged("fDiamondId");
                }
            }
        }
        private Nullable<int> _fDiamondId;
    
        [DataMember]
        public Nullable<int> DiamondId
        {
            get { return _diamondId; }
            set
            {
                if (_diamondId != value)
                {
                    _diamondId = value;
                    OnPropertyChanged("DiamondId");
                }
            }
        }
        private Nullable<int> _diamondId;
    
        [DataMember]
        public Nullable<decimal> DiamondPrice
        {
            get { return _diamondPrice; }
            set
            {
                if (_diamondPrice != value)
                {
                    _diamondPrice = value;
                    OnPropertyChanged("DiamondPrice");
                }
            }
        }
        private Nullable<decimal> _diamondPrice;
    
        [DataMember]
        public Nullable<double> zct
        {
            get { return _zct; }
            set
            {
                if (_zct != value)
                {
                    _zct = value;
                    OnPropertyChanged("zct");
                }
            }
        }
        private Nullable<double> _zct;
    
        [DataMember]
        public string zclarity
        {
            get { return _zclarity; }
            set
            {
                if (_zclarity != value)
                {
                    _zclarity = value;
                    OnPropertyChanged("zclarity");
                }
            }
        }
        private string _zclarity;
    
        [DataMember]
        public string zcolor
        {
            get { return _zcolor; }
            set
            {
                if (_zcolor != value)
                {
                    _zcolor = value;
                    OnPropertyChanged("zcolor");
                }
            }
        }
        private string _zcolor;
    
        [DataMember]
        public string zpolish
        {
            get { return _zpolish; }
            set
            {
                if (_zpolish != value)
                {
                    _zpolish = value;
                    OnPropertyChanged("zpolish");
                }
            }
        }
        private string _zpolish;
    
        [DataMember]
        public string zsymm
        {
            get { return _zsymm; }
            set
            {
                if (_zsymm != value)
                {
                    _zsymm = value;
                    OnPropertyChanged("zsymm");
                }
            }
        }
        private string _zsymm;
    
        [DataMember]
        public string zfluo
        {
            get { return _zfluo; }
            set
            {
                if (_zfluo != value)
                {
                    _zfluo = value;
                    OnPropertyChanged("zfluo");
                }
            }
        }
        private string _zfluo;
    
        [DataMember]
        public string zcut
        {
            get { return _zcut; }
            set
            {
                if (_zcut != value)
                {
                    _zcut = value;
                    OnPropertyChanged("zcut");
                }
            }
        }
        private string _zcut;
    
        [DataMember]
        public Nullable<decimal> MemberPrice
        {
            get { return _memberPrice; }
            set
            {
                if (_memberPrice != value)
                {
                    _memberPrice = value;
                    OnPropertyChanged("MemberPrice");
                }
            }
        }
        private Nullable<decimal> _memberPrice;
    
        [DataMember]
        public Nullable<int> TJLZ
        {
            get { return _tJLZ; }
            set
            {
                if (_tJLZ != value)
                {
                    _tJLZ = value;
                    OnPropertyChanged("TJLZ");
                }
            }
        }
        private Nullable<int> _tJLZ;
    
        [DataMember]
        public Nullable<bool> IsCustomDiamond
        {
            get { return _isCustomDiamond; }
            set
            {
                if (_isCustomDiamond != value)
                {
                    _isCustomDiamond = value;
                    OnPropertyChanged("IsCustomDiamond");
                }
            }
        }
        private Nullable<bool> _isCustomDiamond;
    
        [DataMember]
        public Nullable<int> IsCustomPink
        {
            get { return _isCustomPink; }
            set
            {
                if (_isCustomPink != value)
                {
                    _isCustomPink = value;
                    OnPropertyChanged("IsCustomPink");
                }
            }
        }
        private Nullable<int> _isCustomPink;
    
        [DataMember]
        public Nullable<int> GroupDPID
        {
            get { return _groupDPID; }
            set
            {
                if (_groupDPID != value)
                {
                    _groupDPID = value;
                    OnPropertyChanged("GroupDPID");
                }
            }
        }
        private Nullable<int> _groupDPID;
    
        [DataMember]
        public Nullable<int> znumber
        {
            get { return _znumber; }
            set
            {
                if (_znumber != value)
                {
                    _znumber = value;
                    OnPropertyChanged("znumber");
                }
            }
        }
        private Nullable<int> _znumber;
    
        [DataMember]
        public Nullable<int> fnumber
        {
            get { return _fnumber; }
            set
            {
                if (_fnumber != value)
                {
                    _fnumber = value;
                    OnPropertyChanged("fnumber");
                }
            }
        }
        private Nullable<int> _fnumber;
    
        [DataMember]
        public string CertificateCode
        {
            get { return _certificateCode; }
            set
            {
                if (_certificateCode != value)
                {
                    _certificateCode = value;
                    OnPropertyChanged("CertificateCode");
                }
            }
        }
        private string _certificateCode;
    
        [DataMember]
        public string CertificateType
        {
            get { return _certificateType; }
            set
            {
                if (_certificateType != value)
                {
                    _certificateType = value;
                    OnPropertyChanged("CertificateType");
                }
            }
        }
        private string _certificateType;
    
        [DataMember]
        public string KimWeigth
        {
            get { return _kimWeigth; }
            set
            {
                if (_kimWeigth != value)
                {
                    _kimWeigth = value;
                    OnPropertyChanged("KimWeigth");
                }
            }
        }
        private string _kimWeigth;
    
        [DataMember]
        public string kuanshi
        {
            get { return _kuanshi; }
            set
            {
                if (_kuanshi != value)
                {
                    _kuanshi = value;
                    OnPropertyChanged("kuanshi");
                }
            }
        }
        private string _kuanshi;
    
        [DataMember]
        public string Material
        {
            get { return _material; }
            set
            {
                if (_material != value)
                {
                    _material = value;
                    OnPropertyChanged("Material");
                }
            }
        }
        private string _material;
    
        [DataMember]
        public string HandInch
        {
            get { return _handInch; }
            set
            {
                if (_handInch != value)
                {
                    _handInch = value;
                    OnPropertyChanged("HandInch");
                }
            }
        }
        private string _handInch;
    
        [DataMember]
        public string imgurl
        {
            get { return _imgurl; }
            set
            {
                if (_imgurl != value)
                {
                    _imgurl = value;
                    OnPropertyChanged("imgurl");
                }
            }
        }
        private string _imgurl;
    
        [DataMember]
        public string imgurl2
        {
            get { return _imgurl2; }
            set
            {
                if (_imgurl2 != value)
                {
                    _imgurl2 = value;
                    OnPropertyChanged("imgurl2");
                }
            }
        }
        private string _imgurl2;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
